[build]
  base = "crisissync-app"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://crisissync-api.onrender.com/api/v1"
  NEXT_PUBLIC_WS_URL = "wss://crisissync-api.onrender.com/ws"
